version: '3.8'

services:
  backend:
    build: https://github.com/F1urst/kanban-backend.git
    ports:
      - "8081:8081"

  frontend:
    build: https://github.com/F1urst/kanban-frontend.git
    ports:
      - "8080:8080"
